/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddVacationDrawer: typeof import('./../../features/AddVacation/ui/AddVacationDrawer.vue')['default']
    AppButton: typeof import('./../ui/button/AppButton.vue')['default']
    AppCheckbox: typeof import('./../ui/checkbox/AppCheckbox.vue')['default']
    AppDrawer: typeof import('./../ui/drawer/AppDrawer.vue')['default']
    AppFileUpload: typeof import('./../ui/file-upload/AppFileUpload.vue')['default']
    AppInput: typeof import('./../ui/input/AppInput.vue')['default']
    AppModal: typeof import('./../ui/modal/AppModal.vue')['default']
    AppPagination: typeof import('./../ui/AppPagination/ui/AppPagination.vue')['default']
    AppSelect: typeof import('./../ui/input/AppSelect.vue')['default']
    AppTable: typeof import('./../ui/table/AppTable.vue')['default']
    AppTextarea: typeof import('./../ui/textarea/AppTextarea.vue')['default']
    BrandLogo: typeof import('./../ui/branding/BrandLogo.vue')['default']
    DeleteVacationModal: typeof import('./../../features/DeleteVacation/ui/DeleteVacationModal.vue')['default']
    FormActions: typeof import('./../ui/form/FormActions.vue')['default']
    FormAttachments: typeof import('./../ui/form/FormAttachments.vue')['default']
    Header: typeof import('./../../widgets/Header/ui/Header.vue')['default']
    HeaderActions: typeof import('./../../widgets/Header/ui/HeaderActions.vue')['default']
    HeaderSearchBar: typeof import('./../../widgets/Header/ui/HeaderSearchBar.vue')['default']
    KadrFilterDrawer: typeof import('./../../features/KadrFilter/ui/KadrFilterDrawer.vue')['default']
    KadrFilterModal: typeof import('./../../features/KadrFilter/ui/KadrFilterModal.vue')['default']
    KadrHeader: typeof import('./../../widgets/KadrHeader/ui/KadrHeader.vue')['default']
    KadrModal: typeof import('./../../features/KadrForm/ui/KadrModal.vue')['default']
    KadrTable: typeof import('./../../widgets/KadrTable/ui/KadrTable.vue')['default']
    KadrTableRow: typeof import('./../../widgets/KadrTable/ui/KadrTableRow.vue')['default']
    LoginForm: typeof import('./../../features/auth-by-email/ui/LoginForm.vue')['default']
    MapPickerModal: typeof import('./../../features/create-point/ui/MapPickerModal.vue')['default']
    PageHeader: typeof import('./../ui/PageHeader/PageHeader.vue')['default']
    PointForm: typeof import('./../../features/create-point/ui/PointForm.vue')['default']
    PointGrid: typeof import('./../../widgets/PointGrid/ui/PointGrid.vue')['default']
    PointsHeader: typeof import('./../../widgets/PointsHeader/ui/PointsHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulesHeader: typeof import('./../../widgets/SchedulesHeader/ui/SchedulesHeader.vue')['default']
    SchedulesTable: typeof import('./../../widgets/SchedulesTable/ui/SchedulesTable.vue')['default']
    SchedulesTableRow: typeof import('./../../widgets/SchedulesTable/ui/SchedulesTableRow.vue')['default']
    Sidebar: typeof import('./../../widgets/Sidebar/ui/Sidebar.vue')['default']
    TableActionButtons: typeof import('./../ui/table/TableActionButtons.vue')['default']
    ThemeToggle: typeof import('./../ui/ThemeToggle/ThemeToggle.vue')['default']
    VacationsHeader: typeof import('./../../widgets/VacationsHeader/ui/VacationsHeader.vue')['default']
    VacationsTable: typeof import('./../../widgets/VacationsTable/ui/VacationsTable.vue')['default']
    VacationsTableRow: typeof import('./../../widgets/VacationsTable/ui/VacationsTableRow.vue')['default']
  }
}
