/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../ui/button/AppButton.vue')['default']
    AppCheckbox: typeof import('./../ui/checkbox/AppCheckbox.vue')['default']
    AppInput: typeof import('./../ui/input/AppInput.vue')['default']
    BrandLogo: typeof import('./../ui/branding/BrandLogo.vue')['default']
    LoginForm: typeof import('./../../features/auth-by-email/ui/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./../ui/ThemeToggle/ThemeToggle.vue')['default']
  }
}
